### ISSUE TITLE
lsp-haskell restarts and exits again non-stop (every split second): Arch Linux + Emacs

### ISSUE THREAD

**Issue by ianyepan** [haskell/lsp#369] opened 2021-11-19 22:39 UTC
As titled, I'm on Emacs 27.02 on Arch Linux, with haskell-language-server installed from this recommended AUR package: https://aur.archlinux.org/packages/haskell-language-server-static

When I enter a haskell buffer (with lsp enabled), the server connects and exits abnormally and restarts and exits over and over again, non-stop, (around 5 times / second), flashing the echo area.

Here's a snippet from my Messages buffer:

```txt
LSP :: Connected to [lsp-haskell:7023/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7033/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7043/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7053/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7063/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7073/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7083/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7093/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7103/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7113/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7123/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7133/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7143/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7153/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7163/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
LSP :: Connected to [lsp-haskell:7173/starting].
LSP :: lsp-haskell has exited (exited abnormally with code 1)
```

**Comment by jneira** [comment] 2021-11-20 10:46
Hi, i think the right repo to open the issue is hls, [where you opened the issue as well](https://github.com/haskell/haskell-language-server/issues/2372), so closing this, thanks for reporting!

**Closed by jneira** 2021-11-20 10:46 UTC
